In [ ]:
#---------------------------------------- CUỐI KÌ: TRÍ TUỆ NHÂN TẠO ---------------------------------------- 
# Buổi thực hành 28/09/2024
# Phân lớp, Hồi qui (CK)

In [ ]:
# P------hân lớp

In [ ]:
# Quá trình cơ bản để giải quyết bài toán AI
# Xử lý dữ liệu
# Huấn luyện mô hình
# Đánh giá mô hình
# Triển khai mô hình
# Nhận phản hồi

In [ ]:
# 1. Bài toán phân lớp:
# Ví dụ: phân lớp email spam , email không spam
# Phân lớp bệnh nhân

In [ ]:
# Mô hình trí tuệ nhân tạo học máy
# 1. input
# 2. modal
# 3. output
# Kỹ thuật học giám sát và kỹ thuật không giám sát
# Giám sát: Khi input và ouput nằm trong tập dữ liệu
# Không giám sát: Khi chỉ có input, 

In [6]:
# Kỹ thuật K-NN (Lazy learning)
# Là 1 trong những thuật toán học có giám sát đơn giản nhất được sử dụng nhiều trong khai phá dữ liệu và học máy
# Ý tưởng của thuận toán này là: lưu trữ lại toàn bộ dữ liệu lịch sử mà không rút trích ..,
# dựa vào thiết lập giá trị K, ta tìm 5 phần tử gần giá trị mẫu thử nhất, sau đó tính xác suất xuất hiện của nhãn trong K phần từ. Chọn nhãn xuất hiện nhiều nhất là kết luận.
# Ví dụ:
# Danh sách lớp học sinh giỏi, khá, trung bình
# Hỏi k = 7 là loại gì
# Tìm 5 giá trị gần = 7, nếu là loại gì nhiều nhất => kết luận 


In [ ]:
# xác suất tiền quyết định: là xs của các nhãn phân loại khi đi qua mô hình trước khi được quyết định.
# Ngưỡng quyết định là mốc để đưa ra sự lựa chọn
# Ví dụ:

In [9]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_excel('./heart_short.xlsx')
df.head(15)

t_index  c_index  target
0       145      233       1
1       130      250       1
2       130      204       1
3       130      254       0
4       140      203       0
5       130      256       0
6       140      294       1
7       120      263       1
8       172      199       1
9       150      168       1
10      120      229       0
11      140      268       0

In [17]:
# đổi tên
df.rename(columns={'target': 'result'}, inplace=True)

In [18]:
#
x = df[['t_index', 'c_index']].values
y = df['result'].values

# Đảm bảo dữ liệu là kiểu số thực
x = x.astype(float)
y = y.astype(float)

In [24]:
df.head(12)

t_index  c_index  result          d
0       145      233       1  33.376639
1       130      250       1  53.851648
2       130      204       1  20.396078
3       130      254       0  57.584720
4       140      203       0  10.440307
5       130      256       0  59.464275
6       140      294       1  94.530418
7       120      263       1  69.778220
8       172      199       1  22.022716
9       150      168       1  32.000000
10      120      229       0  41.725292
11      140      268       0  68.731361

In [25]:
# An có X: t_index, c_index = <150,200>
#Dùng công thức euclid tính dX/An
#dx_An = căn bậc hai ((150-143)^2 + (200-233)^2)
# Tính:
# Tính toán dx_An cho từng hàng
import math
def calculate_d(row, t_ref, c_ref):
    return math.sqrt((row['t_index'] - t_ref)**2 + (row['c_index'] - c_ref)**2)

# Tọa độ tham chiếu (có thể thay đổi theo yêu cầu)
t_ref, c_ref = 150, 200

# Áp dụng hàm tính toán dx_An cho toàn bộ dữ liệu
df['d'] = df.apply(calculate_d, axis=1, t_ref=t_ref, c_ref=c_ref)

# In kết quả
print(df)


    t_index  c_index  result          d
0       145      233       1  33.376639
1       130      250       1  53.851648
2       130      204       1  20.396078
3       130      254       0  57.584720
4       140      203       0  10.440307
5       130      256       0  59.464275
6       140      294       1  94.530418
7       120      263       1  69.778220
8       172      199       1  22.022716
9       150      168       1  32.000000
10      120      229       0  41.725292
11      140      268       0  68.731361


In [39]:
# chia tập dữ liệu thành 2 phần với tỉ lệ 60% và 40%
# random_state=34: để cố định việc chia dữ liệu, chú ý cái này của thầy
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, indices_trains, indices_test = train_test_split(x, y, df.index, test_size=0.4, random_state=34)

# print(x_train)
# print(x_test)
# print(y_train)
# print(y_test)
# print(indices_trains)
# print(indices_test)


array([[145., 233.],
       [140., 268.],
       [172., 199.],
       [130., 204.],
       [120., 263.]])

In [37]:
# Huấn luyện mô hình với k = 5
from sklearn.neighbors import KNeighborsClassifier
knnModel = KNeighborsClassifier(n_neighbors=5)
knnModel.fit(x_train, y_train)


KNeighborsClassifier()

In [40]:
# Dự báo mô hình trên tập x_test
# Predicted
y_pred = knnModel.predict(x_test)
y_pred

array([0., 0., 0., 0., 0.])

In [41]:
# đánh giá độ chính xác của mô hình với độ đo Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.2

In [42]:
# Xem nhãn
classes = knnModel.classes_
classes
# Vì có 2 nhãn, là bài toán phân lớp nhị phân

array([0., 1.])

In [43]:
# Tính xác suất tiền quết định trên 
y_pred_prob = knnModel.predict_proba(x_test)
y_pred_prob
# bên cột trái là không bệnh, bên phải là bệnh
# bên trài là chiếm 80% so với 20% bên phải (dòng 1)

array([[0.8, 0.2],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.6, 0.4]])

In [47]:
# Thiết lập ngưỡng (threshold) quyết định là 0.85
# Thì kết quả accuracy thay đổi ra sao
print("prediction with threshold 0.85")
# y_pred_threshold = (y_pred_prob[:,1] >= 0.85).astype(int)
# accuracy_threshold = accuracy_score(y_test, y_pred_threshold)
# accuracy_threshold
y_pred_test_085 = (knnModel.predict_proba(x_test)[:, 1] >= 0.85).astype(float)
y_pred_test_085

prediction with threshold 0.85


array([0., 0., 0., 0., 0.])

In [48]:
# Thiết lập ngưỡng (threshold) quyết định là 0.25
# Thì kết quả accuracy thay đổi ra sao
print("prediction with threshold 0.25")
# y_pred_threshold = (y_pred_prob[:,1] >= 0.25).astype(int)
# accuracy_threshold = accuracy_score(y_test, y_pred_threshold)
# accuracy_threshold
y_pred_test_025 = (knnModel.predict_proba(x_test)[:, 1] >= 0.25).astype(float)
y_pred_test_025

prediction with threshold 0.25


array([0., 1., 1., 1., 1.])

In [ ]:
# Confusion Matrix
# ****** đi thi hỏi dự báo nào đúng: thì chọn TP: 2 cái đều 1,1 là đúng và TN: 2 cái đều là 0, 0 là đúng

# Acc = TP + TN / TP + PP + FN + TN = 1//5
# Đi thi hỏi: với mô hình như này, theo bạn giá trị nào cần giảm tối thiểu trong đây ( cần quan tâm nhất )
# Ví dụ trên thì thằng FN là quan trọng, bởi vì thực tế 1 mà dự báo 0


In [49]:
# Tạo confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm
# Luu ý confusion matrix của python ngược

array([[1, 0],
       [4, 0]], dtype=int64)

In [54]:
# Các giá trị TN, FP, FN, TP
TN, FP, FN, TP = cm.ravel()
TN, FP, FN, TP


(1, 0, 4, 0)

In [ ]:
# Accuracy
# Confusion matrix
# TPR
# AUC & RDC
# Recall, F1, ...